# There are some issues (in the downloading data phase) on MacOS when running with other tests. So we split it into an individual config.
name: Test MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-latest]
        # not supporting 3.6 due to annotations is not supported https://stackoverflow.com/a/52890129
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Lint with Black
      run: |
        cd ..
        python -m pip install pip --upgrade
        python -m pip install wheel --upgrade
        python -m pip install black
        python -m pip install black --version
        python -m black qlib -l 120 --check --diff
    # Test Qlib installed with pip

    - name: Install Qlib with pip
      run: |
          python -m pip install numpy==1.19.5
          python -m pip install pyqlib --ignore-installed ruamel.yaml numpy
          
    - name: Make html with sphnix
      run: |
        pip install -U sphinx
        pip install sphinx_rtd_theme readthedocs_sphinx_ext
        pip install --exists-action=w --no-cache-dir -r docs/requirements.txt 
        cd docs 
        sphinx-build -b html . build
