name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-20.04]
        # not supporting 3.6 due to annotations is not supported https://stackoverflow.com/a/52890129
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Qlib with pip
      run: |
        pip install Cython
        pip install numpy==1.19.5 ruamel.yaml
        pip install pyqlib --ignore-installed
        
    - name: Make html with sphnix
      run: |
        cd docs
        pip install -U sphinx
        pip install sphinx_rtd_theme readthedocs_sphinx_ext
        pip install --exists-action=w --no-cache-dir -r docs/requirements.txt 
        sphinx-build html . build

